[package]
name = "skye"
version = "2024.8.30"
edition = "2021"
description = "Skye ~ The retrofuturistic programming language"

[dependencies]
colored = "2.1.0"
clap = { version = "4.5.13", features = ["derive"] }
convert_case = "0.6.0"
